name: LagFixer
description: Get rid of invisible players and get your correct health
api: [2.0.0]
author: PEMapModder
version: 1.0
main: pemapmodder\lagfixer\LagFixer
website: https://github.com/PEMapModder/Small-ZC-Plugins/tree/master/LagFixer
permissions:
  lagfixer:
    description: Allows using everything of LagFixer
    children:
      lagfixer.show:
        description: Allows using /show
        children:
          lagfixer.show.player:
            default: true
            description: Allows using /show <player>
          lagfixer.show.all:
            default: true
            description: Allows using /show -all
      lagfixer.realhealth:
        description: Allows using /realhealth
        default: true

