--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PEMapModder/Small-ZC-Plugins
projects:
  BulkCommands:
    path: BulkCommands/
  ChatLineBreaker:
    path: ChatLineBreaker/
  CommandSelectors:
    path: CommandSelectors/
  ConsolePush:
    path: ConsolePush/
  DynamicSignTechnology:
    path: DynamicSignTechnology/
  IPLogger:
    path: IPLogger/
  IRCBridge:
    path: IRCBridge/
  InfoEssentials:
    path: InfoEssentials/
  LagFixer:
    path: LagFixer/
  Mist:
    path: Mist/
  NailedKeyboard:
    path: NailedKeyboard/
  NameCorrector:
    path: NameCorrector/
  NumericRanks:
    path: NumericRanks/
  PastebinPoster:
    path: PastebinPoster/
  RemoteChat:
    path: RemoteChat/
  SimpleMacros:
    path: SimpleMacros/
    icon: icon.png
  WorldEditArt:
    path: WorldEditArt/
...
