---
name: SpicyCapacitor
author: PEMapModder
api:
- 1.0.0
version: 1.0.0_dev#000
main: pemapmodder\spicycap\SpicyCap
permissions:
  spicycap:
    description: Allows using all permissions of SpiyCapacitor
...
