---
#### Data providers
## Data providers provide the plugin storages to store data
data providers:
  # Player data provider provides the plugin per-player data, such as personal wands
  player:
    # Choose a data provider type. Options:
    # sqlite3 (create an SQLite3 file as database)
    # yaml (save one YAML file for each player)
    # json (save one JSON file for each player)
    # mysqli (save on a remote MySQL database)
    type: sqlite3
    # SQLite3 options. If you use it, configure this properly.
    sqlite3:
      # The path to save the database. It will be saved in /.../PocketMine-MP/plugins/WorldEditArt/<path>. Enter <path> below. (Sub-folders will NOT be created automatically; create the directories yourself; use .. to jump up to parent folder)
      path: "players.sq3"
    # YAML options. If you use it, configure this properly.
    yaml:
      # The path to save files. It will be saved in /.../PocketMine-MP/plugins/WorldEditArt/<path>. Enter <path> below. (Sub-folders will be created automatically; you just need to use / (or / or \\ if on Windows); use .. to jump up to parent folder)
      path: "players/yaml/<name>.yml"
    # JSON options. If you use it, configure this properly.
    json:
      # The path to save files. It will be saved in /.../PocketMine-MP/plugins/WorldEditArt/<path>. Enter <path> below. (Sub-folders will be created automatically; you just need to use / (or / or \\ if on Windows); use .. to jump up to parent folder)
      path: "players/json/<name>.json"
      # Format the files beautifully. This will write unnecessary (and ignored when reading) indents and returns that eases your reading if you open/modify these files.
      pretty print: true
    # MySQLi options. If you use it, configure this properly.
    mysqli:
      use common: true
      host: example.com
      username: "guest"
      password: "123456IsNotAGoodPassword"
      database: "WorldEditArt player database"
      port: 3306

  macro:
    # Macros can be provided by multiple providers.
    databases:
      default:
        # Options:
        # mcr: Saves using the NBT-oriented .mcr database
        # mysqli: Connects to a remote MySQLi database for macros
        # ram: Saves macros in RAM, which will be deleted when the server stops/reloads. Only use this when you don't want to save any macros, or expect another plugin to set another provider.
        type: mcr
        # If you don't want new macros to be saved into the database,
        # or if you don't have write access to the database, set this to true
        # If you don't have permision to write that database, you must set this to true
        # Otherwise, the server may crash
        read-only: false
        # If the database name is default, this database will be loaded regardless of this setting.
        enabled: true
        config:
          # path inside plugin folder
          path: "macros/<name>.mcr"
          is phar: false
          compression: 0
      builtin:
        type: mcr
        read-only: true
        enabled: true
        config:
          # res://path.ext jumps to the resources path of the plugin
          # The files in the resources path can be
          path: "res://defaults/<name>.mcr"
          compression: 0
      online:
        type: mysqli
        read-only: false
        enabled: false
        config:
          # Whether or not to use the common database.
          # If set to true, host, username, password, database and port here aren't needed.
          use common: false
          host: example.com
          username: "guest"
          password: "123456AintGoodPassword"
          database: "WorldEditArt database"
          port: 3306

  # Clipboard data provider provides the plugin a clipboard to store clips
  clipboard:
    # Choose a data provider type. Options:
    # clp (save one .clp file for each clip)
    # mysqli (save on a remote MySQL database)
    type: clp
    # CLP options. If you use it, configure this properly.
    clp:
      # The path to save files. It will be saved in /.../PocketMine-MP/plugins/WorldEditArt/<path>. Enter <path> below. (Sub-folders will be created automatically; you just need to use / (or / or \\ if on Windows); use .. to jump up to parent folder)
      path: "clipboard/<name>.clp"
    # MySQLi options. If you use it, configure this properly.
    mysqli:
      use common: true
      host: example.com
      username: "guest"
      password: "123456IsNotAGoodPassword"
      database: "WorldEditArt macro database"
      port: 3306

  # If you want all mysqli data providers to use the same mysqli database, configure this and set "use common" to true in each of them
  common mysqli database:
    host: example.com
    username: "guest"
    password: "123456IsNotAGoodPassword"
    database: "WorldEditArt_common_database"
    port: 3306
  # To increase efficiency, loaded data is saved in memory as "caches". How many seconds should these data be held in memory before collected (i.e. deleted) by the plugin?
  cache time: 120

#### Wands
# Wands set your anchor to the block you are pointing at
# The default wand item ID
wand-id: 292
# leave false for any values
wand-damage: false

#### Jump
# Jump is a feature where you click the screen with a specified item and you are teleported to the block your crosshair points at
# The default jump item ID
jump-id: 345
# leave false for any values
jump-damage: 0

#### Version compatibility
## Changing these value could lead to dangerous crashes.
# If PocketMine and MCPE are updated such that the world maximum height is no longer 127, change this. This value is NOT to increase the world height. It is only an in-case support in case MCPE now supports higher worlds but this plugin is not yet updated.
maximum world height: 127
