---
name: NailedKeyboard
version: 1.1.0_dev_build_001
api:
- 1.0.0
main: pemapmodder\nailedkeyboard\NailedKeyboard
permissions:
  nailedkeyboard:
    description: Using NailedKeyboard
    default: true
...
