---
name: ThirdPersonDiscourager
version: "1.010"
api: 2.0.0
author: PEMapModder
main: thirdpersondiscour\ThirdPersonDiscour
permissions:
  thirdpersondiscour:
    description: Allows running command /3pdc
    default: op
commands:
  3pdc:
    description: Discourage/Un-discourage/Check a player from using third person
    usage: /3pdc <player> [.check]
    permission: thirdpersondiscour
...
