---
name: ThirdPersonDiscourager
version: "1.003"
api: 1.5.0
author: PEMapModder
main: thirdpersondiscour\ThirdPersonDiscour
permissions:
  thirdpersondiscour:
    description: Allows running command /3pdc
    default: op
commands:
  3pdc:
    description: Discourage/Un-discourage a player from using third person
    usage: /3pdc <player>
    permission: thirdpersondiscour
...
