name: DeFactoGui
version: 2.0.0_build#000
api: 2.0.0
main: defactogui\DeFactoGui
website: https://github.com/PEMapModder/Small-ZC-Plugins/tree/DeFactoGui
author: PEMapModder
description: MCPE commands are terrible. Use GUI instead.
