---
name: Spacefiller
version: "1.001"
api: 1.0.0
description: Replaces spaces with one space. Also allows customizable Regex chat message
  processing.
author: PEMapModder
main: spacefiller\Spacefiller
...
