---
dataProvider: yaml
ranks:
  Player:
    defaultRank: true
    index: 0
  Trusted:
    index: 100
  Admin:
    index: 150
  Owner:
    index: 200
defaultPermissionIndex:
  true: 0
  notOp: 0
  op: 150
  false: 999
...
