name: PastebinPoster
version: 0.0
api: [2.0.0]
main: pemapmodder\pastebinposter\Main
author: PEMapModder
website: https://github.com/PEMapModder/Small-ZC-Plugins/tree/master/PastebinPoster
commands:
  post:
    description: Posts a paste to http://pastebin.com
    usage: <duration> [privacy = public] <content ...>
permissions:
  pastebinposter:
    description: Allows using all features of PastebinPoster
    children:
      pastebinposter.post:
        description: Allows posting any pastes to pastebin.com
        children:
          pastebinposter.post.public:
            description: Allows posting public posts to pastebin.com
          pastebinposter.post.public:
            description: Allows posting public posts to pastebin.com
          pastebinposter.post.public:
            description: Allows posting public posts to pastebin.com
