---
# DirectAuth options
directauth:
  # maximum number of failures allowed before kicking player
  max-failures: 5
  # file for logging login failure attempts using DirectAuth
  # if you don't want AuthTools to log failures, put "/dev/null" here
  # if you wish to use absolute paths (do not include the drive name if you are on Windows), put "//" then the absolute path of the desired log file
  # if you are on Windows and want to store the path on a file at another drive, use the normal absolute path format, e.g. "Z:/path/to/my/file.log"
  # otherwise, put the relative path of the desired log file relative to AuthTools data folder directly, such as "failures.log"
  # the file will be automatically created if it is not equal to "/dev/null"
  # to avoid accidental user bugs, you are encouraged to use "/" rather than "\" if you are on Windows
  log-file: /dev/null
...
